-- Create roles
CREATE ROLE DATA_ENGINEER;
CREATE ROLE DATA_ANALYST;
CREATE ROLE REPORTER;

-- Grant warehouse access
GRANT USAGE ON WAREHOUSE CARWASH_WH TO ROLE DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE CARWASH_WH TO ROLE DATA_ANALYST;

-- Grant database access
GRANT ALL ON DATABASE CARWASH_RAW       TO ROLE DATA_ENGINEER;
GRANT ALL ON DATABASE CARWASH_ANALYTICS TO ROLE DATA_ENGINEER;
GRANT USAGE ON DATABASE CARWASH_ANALYTICS TO ROLE DATA_ANALYST;
GRANT USAGE ON SCHEMA CARWASH_ANALYTICS.REPORTING TO ROLE REPORTER;
